spring:
  application:
    name: sistema-escolar
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_escolar
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
